Pandas is a Python library used to store, organize, clean, and analyze data in table format

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print(pd.__version__)

2.2.2

A Pandas Series is a one-dimensional labeled array used to store a single column of data in pandas.

In [ ]:
#from list
ser=pd.Series([1,2,3,4,5])
print(ser)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#custom index
ser=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(ser)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
student={
    "name":"sireesha",
    "branch":"aiml"
}
se=pd.Series(student)
print(se)

name      sireesha
branch        aiml
dtype: object

In [ ]:
A=pd.Series([5,6,9,8,7])

In [ ]:
A+2

0     7
1     8
2    11
3    10
4     9
dtype: int64

In [ ]:
A*3

0    15
1    18
2    27
3    24
4    21
dtype: int64

In [ ]:
A.mean()

np.float64(7.0)

In [ ]:
A.sum()

np.int64(35)

In [ ]:
A.max()

9

In [ ]:
A.describe()

count    5.000000
mean     7.000000
std      1.581139
min      5.000000
25%      6.000000
50%      7.000000
75%      8.000000
max      9.000000
dtype: float64

In [ ]:
# Boolean indexing
A[A > 3]

0    5
1    6
2    9
3    8
4    7
dtype: int64

In [ ]:
# Vectorized string operations
names = pd.Series(['Siree', 'suma', 'renu'])
names.str.lower()
names.str.len()
names.str.startswith('S')

0     True
1    False
2    False
dtype: bool

A DataFrame is a two-dimensional table in pandas used to store data in rows and columns.

In [ ]:
 # From dictionary
student = {
    'Name':   ['siree', 'suma', 'renu', 'iqra'],
    'Age':    [23, 25, 22, 28],
    'Score':  [88, 75, 92, 81],
    'Grade':  ['A', 'B', 'A', 'A']
}
a = pd.DataFrame(student)
print(a)

    Name  Age  Score Grade
0  siree   23     88     A
1   suma   25     75     B
2   renu   22     92     A
3   iqra   28     81     A

In [ ]:
student = [{'name': 'siree', 'age': 23}, {'names': 'devika', 'age': 18}]
b = pd.DataFrame(student)
print(b)

    name  age   names
0  siree   23     NaN
1    NaN   18  devika

In [ ]:
# From NumPy array
arr = np.random.rand(4, 4)
c = pd.DataFrame(arr, columns=['A','B','C','D'], index=['x','y','z','u'])
print(c)

          A         B         C         D
x  0.067627  0.895444  0.810433  0.938649
y  0.395881  0.088152  0.566516  0.862980
z  0.677890  0.941273  0.834002  0.710679
u  0.085897  0.982980  0.831974  0.012228

In [ ]:
# Exporing Data Frame

data = {
    'Name':   ['siree', 'renu', 'suma', 'iqra'],
    'Age':    [23, 25, 22, 28],
    'Score':  [95, 82, 92, 81],
    'Grade':  ['A', 'B', 'A', 'A']
}
d = pd.DataFrame(data)

In [ ]:
print(d.head(3))
print(d.tail(3))
print(d.shape)
print(d.info())
print(d.describe())
print(d.columns)
print(d.index)
print(d.dtypes)
print(d.nunique())
print(d.isnull().sum())

    Name  Age  Score Grade
0  siree   23     95     A
1   renu   25     82     B
2   suma   22     92     A
   Name  Age  Score Grade
1  renu   25     82     B
2  suma   22     92     A
3  iqra   28     81     A
(4, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
 3   Grade   4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes
None
             Age      Score
count   4.000000   4.000000
mean   24.500000  87.500000
std     2.645751   7.047458
min    22.000000  81.000000
25%    22.750000  81.750000
50%    24.000000  87.000000
75%    25.750000  92.750000
max    28.000000  95.000000
Index(['Name', 'Age', 'Score', 'Grade'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
Name     object
Age       int64
Score     int64
Grade    object
dtype: object
Name     4
Age      4
Score    4
Grade    2
dtype: int64
Name     0
Age      0
Score    0
Grade    0
dtype: int64

In [ ]:
d['Name']

0    siree
1     renu
2     suma
3     iqra
Name: Name, dtype: object

In [ ]:
d.Name

0    siree
1     renu
2     suma
3     iqra
Name: Name, dtype: object

In [ ]:
d[['Name', 'Score']]

    Name  Score
0  siree     95
1   renu     82
2   suma     92
3   iqra     81

In [ ]:
d.loc[0]

Name     siree
Age         23
Score       95
Grade        A
Name: 0, dtype: object

In [ ]:
d.loc[0:2]

    Name  Age  Score Grade
0  siree   23     95     A
1   renu   25     82     B
2   suma   22     92     A

In [ ]:
d.loc[0:2, 'Name':'Score']

    Name  Age  Score
0  siree   23     95
1   renu   25     82
2   suma   22     92

In [ ]:
print(d.iloc[0])
print(d.iloc[0:2])
print(d.iloc[0:2 , 0:2])
print(d.iloc[-1])

Name     siree
Age         23
Score       95
Grade        A
Name: 0, dtype: object
    Name  Age  Score Grade
0  siree   23     95     A
1   renu   25     82     B
    Name  Age
0  siree   23
1   renu   25
Name     iqra
Age        28
Score      81
Grade       A
Name: 3, dtype: object

In [ ]:
d.loc[0, 'Name']

'siree'

In [ ]:
d.iloc[0, 0]

'siree'

In [ ]:
d[(d['Score'] > 80)]

    Name  Age  Score Grade
0  siree   23     95     A
1   renu   25     82     B
2   suma   22     92     A
3   iqra   28     81     A

In [ ]:
# Multiple conditions: use & (and) | (or) ~ (not)
d[(d['Score'] > 80) & (d['Grade'] == 'A')]
d[(d['Age'] < 24) | (d['Score'] > 90)]

    Name  Age  Score Grade
0  siree   23     95     A
2   suma   22     92     A

In [ ]:
d.query('Score > 80 and Age < 25')
d.query('Grade == "A"')

    Name  Age  Score Grade
0  siree   23     95     A
2   suma   22     92     A
3   iqra   28     81     A

In [ ]:
d[d['Name'].isin(['siree', 'devika'])]

    Name  Age  Score Grade
0  siree   23     95     A

In [ ]:
d['grade']=d['Score']>=80

In [ ]:
d['example']=["a","b","c","d"]

In [ ]:
d['percentage'] = d['Score'] * 0.1
d['Pass'] = d['Score'] >= 80
print(d)

    Name  Age  Score Grade  grade example  percentage  Pass
0  siree   23     95     A   True       a         9.5  True
1   renu   25     82     B   True       b         8.2  True
2   suma   22     92     A   True       c         9.2  True
3   iqra   28     81     A   True       d         8.1  True

In [ ]:
print(d)

    Name  Age  Score Grade  grade example  percentage  Pass
0  siree   23     95     A   True       a         9.5  True
1   renu   25     82     B   True       b         8.2  True
2   suma   22     92     A   True       c         9.2  True
3   iqra   28     81     A   True       d         8.1  True

In [ ]:
d['Score']=d['Score']+5

In [ ]:
def grade(Score):
  if (Score>=90):
    return 'A'
  elif (Score>=60 and Score<80):
      return 'B'
  else:
    return "fail"
print(d)

    Name  Age  Score Grade  grade example  percentage  Pass
0  siree   23    100     A   True       a         9.5  True
1   renu   25     87     B   True       b         8.2  True
2   suma   22     97     A   True       c         9.2  True
3   iqra   28     86     A   True       d         8.1  True

In [ ]:
result={
    True:"pass",
    False:"fail"
}
pas={'A':90,'B':80,'D':60}

In [ ]:
d['pass']=d['Grade'].map(pas)
d['result']=d['grade'].map(result)
print(d)

    Name  Age  Score Grade  grade example  percentage  Pass  pass result
0  siree   23    100     A   True       a         9.5  True    90   pass
1   renu   25     87     B   True       b         8.2  True    80   pass
2   suma   22     97     A   True       c         9.2  True    90   pass
3   iqra   28     86     A   True       d         8.1  True    90   pass

In [ ]:
d.drop('pass', axis=1, inplace=True)
d.drop(columns=['Pass', 'percentage'], inplace=True)
print(d)

    Name  Age  Score Grade  grade example result
0  siree   23    100     A   True       a   pass
1   renu   25     87     B   True       b   pass
2   suma   22     97     A   True       c   pass
3   iqra   28     86     A   True       d   pass

In [ ]:
d.rename(columns={'Score':'marks','Name':'student'}, inplace=True)
print(d)

  student  Age  marks Grade  grade example result
0   siree   23    100     A   True       a   pass
1    renu   25     87     B   True       b   pass
2    suma   22     97     A   True       c   pass
3    iqra   28     86     A   True       d   pass

In [ ]:
d.fillna(0)
d['Age'].fillna(d['Age'].mean(), inplace=True)
print(d)

  student  Age  marks Grade  grade example result
0   siree   23    100     A   True       a   pass
1    renu   25     87     B   True       b   pass
2    suma   22     97     A   True       c   pass
3    iqra   28     86     A   True       d   pass

/tmp/ipykernel_2259/873466.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Age'].fillna(d['Age'].mean(), inplace=True)

In [ ]:
d.replace('B',np.nan, inplace=True)
print(d)

  student  Age  marks Grade  grade example result
0   siree   23    100     A   True       a   pass
1    renu   25     87   NaN   True       b   pass
2    suma   22     97     A   True       c   pass
3    iqra   28     86     A   True       d   pass

In [ ]:
d.sort_values('marks',ascending=True)

  student  Age  marks Grade  grade example result
3    iqra   28     86     A   True       d   pass
1    renu   25     87   NaN   True       b   pass
2    suma   22     97     A   True       c   pass
0   siree   23    100     A   True       a   pass

In [ ]:
d.sort_index(ascending=False)

  student  Age  marks Grade  grade example result
3    iqra   28     86     A   True       d   pass
2    suma   22     97     A   True       c   pass
1    renu   25     87   NaN   True       b   pass
0   siree   23    100     A   True       a   pass

In [ ]:
d.nlargest(4, 'marks')
d.nsmallest(3, 'Age')

  student  Age  marks Grade  grade example result
2    suma   22     97     A   True       c   pass
0   siree   23    100     A   True       a   pass
1    renu   25     87   NaN   True       b   pass

In [ ]:
data = {
    'Department': ['IT','HR','IT','HR','IT'],
    'Name': ['siree','suma','renu','iqra','devi'],
    'Salary': [70000, 50000, 80000, 55000, 75000],
    'YearsExp': [3, 5, 7, 2, 4]
}
df = pd.DataFrame(data)
print(df)

  Department   Name  Salary  YearsExp
0         IT  siree   70000         3
1         HR   suma   50000         5
2         IT   renu   80000         7
3         HR   iqra   55000         2
4         IT   devi   75000         4

In [ ]:
df.groupby('Department')['Salary'].max()

Department
HR    55000
IT    80000
Name: Salary, dtype: int64

In [ ]:
employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4],
    'name': ['siree','suma','renu','iqra'],
    'dept_id': [10, 20, 10, 30]
})

departments = pd.DataFrame({
    'dept_id': [10, 20],
    'dept_name': ['Engineering', 'HR']
})

In [ ]:
pd.merge(employees, departments, on='dept_id', how='inner')

   emp_id   name  dept_id    dept_name
0       1  siree       10  Engineering
1       2   suma       20           HR
2       3   renu       10  Engineering

In [ ]:
pd.merge(employees, departments, on='dept_id', how='left')

   emp_id   name  dept_id    dept_name
0       1  siree       10  Engineering
1       2   suma       20           HR
2       3   renu       10  Engineering
3       4   iqra       30          NaN